backend:
  name: git-gateway
  branch: master

media_folder: "public/static"
public_folder: "/static"

collections:
  - name: "docs"
    label: "Docs"
    folder: "pages/docs"
    identifier_field: title
    extension: mdx
    widget: "list"
    create: true
    slug: "{{slug}}"
    media_folder: "public/static/docs"
    public_folder: "/static/docs"
    filter: '!!path.match(/pages\\/docs\\/[^\\/]+\\.mdx$/)'
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "interview"
    label: "Interview"
    folder: "pages/interview"
    identifier_field: title
    extension: mdx
    widget: "list"
    create: true
    slug: "{{slug}}"
    media_folder: "public/static/interview"
    public_folder: "/static/interview"
    filter: '!!path.match(/pages\\/interview\\/[^\\/]+\\.mdx$/)'
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "blog"
    label: "Blog"
    folder: "pages/blog"
    identifier_field: title
    extension: mdx
    widget: "list"
    create: true
    slug: "{{slug}}"
    filter: '!!path.match(/pages\\/blog\\/[^\\/]+\\.mdx$/)'
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Image", widget: "image" }
